import { useEffect, useState, type FormEvent } from "react"
import { ArrowLeft, Ban, Building2, Clock3, Edit3, Mail, PauseCircle, PlayCircle, Plus, RefreshCw, UserPlus, UserRound, UserX, Users } from "lucide-react"
import { createOrganization, disableOrganizationMembership, listOrganizationUsers, listOrganizations, revokeOrganizationInvitation, sendManagerInvitation, setOrganizationStatus, updateOrganization } from "../services/organizations"
import type { CreateOrganizationInput, OrganizationStatus, OrganizationSummary, OrganizationUserRecord } from "../types/organization"

type AdminTab = "summary" | "users" | "tickets"
const formatDate = (value: string) => new Intl.DateTimeFormat("es-MX", { dateStyle: "medium" }).format(new Date(value))

export function AdminOrganizationsPage({ onFeedback }: { onFeedback: (message: string) => void }) {
  const [organizations, setOrganizations] = useState<OrganizationSummary[]>([])
  const [selectedOrganizationId, setSelectedOrganizationId] = useState<string | null>(null)
  const [activeTab, setActiveTab] = useState<AdminTab>("summary")
  const [isLoading, setIsLoading] = useState(true)
  const [loadError, setLoadError] = useState<string | null>(null)
  const [isFormOpen, setIsFormOpen] = useState(false)
  const [editingOrganization, setEditingOrganization] = useState<OrganizationSummary | null>(null)
  const [isSaving, setIsSaving] = useState(false)

  const loadOrganizations = async () => {
    setIsLoading(true); setLoadError(null)
    try {
      const items = await listOrganizations()
      setOrganizations(items)
      setSelectedOrganizationId((current) => current && items.some((item) => item.id === current) ? current : null)
    } catch (error) { setLoadError(error instanceof Error ? error.message : "No se pudieron cargar las empresas.") }
    finally { setIsLoading(false) }
  }
  useEffect(() => { void loadOrganizations() }, [])
  const selectedOrganization = organizations.find((item) => item.id === selectedOrganizationId) ?? null
  const openCreateForm = () => { setEditingOrganization(null); setIsFormOpen(true) }
  const openEditForm = () => { if (selectedOrganization) { setEditingOrganization(selectedOrganization); setIsFormOpen(true) } }
  const handleSave = async (input: CreateOrganizationInput) => {
    setIsSaving(true)
    try {
      const saved = editingOrganization ? await updateOrganization({ ...input, organizationId: editingOrganization.id }) : await createOrganization(input)
      setIsFormOpen(false); setSelectedOrganizationId(saved.id); await loadOrganizations()
      onFeedback(editingOrganization ? "Empresa actualizada correctamente." : "Empresa creada correctamente.")
    } catch (error) { throw error instanceof Error ? error : new Error("No se pudo guardar la empresa.") }
    finally { setIsSaving(false) }
  }
  const handleStatusChange = async () => {
    if (!selectedOrganization) return
    const nextStatus: OrganizationStatus = selectedOrganization.status === "active" ? "suspended" : "active"
    if (nextStatus === "suspended" && !window.confirm("La empresa conservará sus datos, pero quedará marcada como suspendida. ¿Deseas continuar?")) return
    setIsSaving(true)
    try { await setOrganizationStatus(selectedOrganization.id, nextStatus); await loadOrganizations(); onFeedback(nextStatus === "suspended" ? "Empresa suspendida." : "Empresa reactivada.") }
    catch (error) { setLoadError(error instanceof Error ? error.message : "No se pudo actualizar el estado de la empresa.") }
    finally { setIsSaving(false) }
  }

  if (selectedOrganization) return <section className="admin-page">
    <button className="summary-back-button" onClick={() => setSelectedOrganizationId(null)} type="button"><ArrowLeft aria-hidden="true" size={18} /> Empresas</button>
    <header className="admin-detail-header"><div><p>Empresa</p><h1>{selectedOrganization.name}</h1><span>Alta: {formatDate(selectedOrganization.createdAt)}</span></div><div className="admin-detail-actions"><span className={`organization-status organization-status--${selectedOrganization.status}`}>{selectedOrganization.status === "active" ? "Activa" : "Suspendida"}</span><button className="button button--secondary" onClick={openEditForm} type="button"><Edit3 aria-hidden="true" size={17} /> Editar</button><button className="button button--secondary" disabled={isSaving} onClick={() => void handleStatusChange()} type="button">{selectedOrganization.status === "active" ? <PauseCircle aria-hidden="true" size={17} /> : <PlayCircle aria-hidden="true" size={17} />}{selectedOrganization.status === "active" ? "Suspender" : "Reactivar"}</button></div></header>
    <nav className="admin-tabs" aria-label="Secciones de empresa">{(["summary", "users", "tickets"] as const).map((tab) => <button className={activeTab === tab ? "admin-tab admin-tab--active" : "admin-tab"} key={tab} onClick={() => setActiveTab(tab)} type="button">{tab === "summary" ? "Resumen" : tab === "users" ? "Usuarios" : "Tickets"}</button>)}</nav>
    {activeTab === "summary" ? <section className="organization-summary-grid"><div className="organization-summary-card"><span>Usuarios utilizados</span><strong>{selectedOrganization.seatsUsed} de {selectedOrganization.seatLimit}</strong><small>Plazas ocupadas</small></div><div className="organization-summary-card"><span>Disponibles</span><strong>{selectedOrganization.seatsAvailable}</strong><small>Plazas restantes</small></div><div className="organization-summary-card"><span>Estado</span><strong>{selectedOrganization.status === "active" ? "Activa" : "Suspendida"}</strong><small>{selectedOrganization.suspendedAt ? `Desde ${formatDate(selectedOrganization.suspendedAt)}` : "Operación habilitada"}</small></div></section> : activeTab === "users" ? <OrganizationUsers organization={selectedOrganization} isSaving={isSaving} onFeedback={onFeedback} onRefreshOrganizations={loadOrganizations} onSavingChange={setIsSaving} /> : <div className="admin-coming-soon"><Building2 aria-hidden="true" size={28} /><strong>Tickets</strong><span>Esta sección estará disponible en una siguiente fase.</span></div>}
    {isFormOpen ? <OrganizationForm editingOrganization={editingOrganization} isSaving={isSaving} onClose={() => setIsFormOpen(false)} onSubmit={handleSave} /> : null}
  </section>

  return <section className="admin-page"><header className="page-header"><div><p>Administración</p><h1>Empresas</h1><span>Administra las empresas y sus límites de usuarios.</span></div><button className="button button--primary" onClick={openCreateForm} type="button"><Plus aria-hidden="true" size={18} /> Nueva empresa</button></header>{isLoading ? <div className="state-card">Cargando empresas...</div> : loadError ? <div className="state-card state-card--warning"><strong>No se pudieron cargar las empresas</strong><span>{loadError}</span></div> : organizations.length === 0 ? <div className="empty-state admin-empty-state"><Building2 aria-hidden="true" size={34} /><strong>No hay empresas registradas</strong><span>Crea la primera empresa para comenzar a organizar FleetMaster.</span><button className="button button--primary" onClick={openCreateForm} type="button"><Plus aria-hidden="true" size={18} /> Nueva empresa</button></div> : <div className="organization-list">{organizations.map((organization) => <button className="organization-row" key={organization.id} onClick={() => { setSelectedOrganizationId(organization.id); setActiveTab("summary") }} type="button"><span className="organization-row__icon"><Building2 aria-hidden="true" size={20} /></span><span className="organization-row__content"><strong>{organization.name}</strong><small>Usuarios: {organization.seatsUsed} de {organization.seatLimit} · Alta: {formatDate(organization.createdAt)}</small></span><span className={`organization-status organization-status--${organization.status}`}>{organization.status === "active" ? "Activa" : "Suspendida"}</span><span className="organization-row__arrow" aria-hidden="true">→</span></button>)}</div>}{isFormOpen ? <OrganizationForm editingOrganization={editingOrganization} isSaving={isSaving} onClose={() => setIsFormOpen(false)} onSubmit={handleSave} /> : null}</section>
}

function OrganizationUsers({ organization, isSaving, onFeedback, onRefreshOrganizations, onSavingChange }: { organization: OrganizationSummary; isSaving: boolean; onFeedback: (message: string) => void; onRefreshOrganizations: () => Promise<void>; onSavingChange: (value: boolean) => void }) {
  const [users, setUsers] = useState<OrganizationUserRecord[]>([]); const [isLoading, setIsLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [isInviteOpen, setIsInviteOpen] = useState(false)
  const loadUsers = async () => { setIsLoading(true); setError(null); try { setUsers(await listOrganizationUsers(organization.id)) } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "No se pudieron cargar los usuarios.") } finally { setIsLoading(false) } }
  useEffect(() => { void loadUsers() }, [organization.id])
  const manager = users.find((item) => item.role === "manager"); const hasAssignedManager = Boolean(manager && ((manager.recordType === "invitation" && manager.status === "pending") || (manager.recordType === "membership" && manager.status === "active"))); const otherUsers = users.filter((item) => item.role !== "manager"); const isAtLimit = organization.seatsUsed >= organization.seatLimit; const actionsDisabled = isSaving || organization.status !== "active" || isAtLimit
  const handleRevoke = async (item: OrganizationUserRecord) => { if (!window.confirm(`¿Revocar la invitación para ${item.email}?`)) return; onSavingChange(true); try { await revokeOrganizationInvitation(item.id); await Promise.all([loadUsers(), onRefreshOrganizations()]); onFeedback("Invitación revocada. La plaza está disponible nuevamente.") } catch (actionError) { setError(actionError instanceof Error ? actionError.message : "No se pudo revocar la invitación.") } finally { onSavingChange(false) } }
  const handleDisable = async (item: OrganizationUserRecord) => { if (!window.confirm(`¿Desactivar a ${item.displayName || item.email}?`)) return; onSavingChange(true); try { await disableOrganizationMembership(item.id); await Promise.all([loadUsers(), onRefreshOrganizations()]); onFeedback("Usuario desactivado.") } catch (actionError) { setError(actionError instanceof Error ? actionError.message : "No se pudo desactivar el usuario.") } finally { onSavingChange(false) } }
  const submitInvitation = async (name: string, email: string) => { onSavingChange(true); try { await sendManagerInvitation({ organizationId: organization.id, name, email }); setIsInviteOpen(false); await Promise.all([loadUsers(), onRefreshOrganizations()]); onFeedback("Invitación enviada correctamente. Se reservó una plaza para el usuario.") } finally { onSavingChange(false) } }
  return <section className="organization-users"><header className="users-panel-header"><div><p>Usuarios</p><h2>Personas de la empresa</h2><span>Las invitaciones registradas reservan una plaza.</span></div><div className="users-seat-count"><strong>{organization.seatsUsed} de {organization.seatLimit}</strong><span>{organization.seatsAvailable} disponibles</span></div></header>{organization.status !== "active" ? <div className="users-notice"><Ban aria-hidden="true" size={17} /> La empresa está suspendida. No se pueden registrar invitaciones.</div> : null}{isAtLimit ? <div className="users-notice users-notice--limit"><Users aria-hidden="true" size={17} /> Se alcanzó el límite de plazas.</div> : null}<section className="users-section"><header><div><p>Responsable de la empresa</p><h3>Manager principal</h3></div><button className="button button--primary" disabled={actionsDisabled || hasAssignedManager} onClick={() => setIsInviteOpen(true)} type="button"><UserPlus aria-hidden="true" size={17} /> Asignar Manager</button></header>{isLoading ? <div className="users-empty">Cargando usuarios...</div> : manager ? <UserRecord item={manager} onDisable={manager.recordType === "membership" && manager.status === "active" ? () => void handleDisable(manager) : undefined} onRevoke={manager.recordType === "invitation" && manager.status === "pending" ? () => void handleRevoke(manager) : undefined} /> : <div className="users-empty"><UserRound aria-hidden="true" size={25} /><strong>Aún no se ha asignado un responsable.</strong><span>Registra una invitación para el Manager principal.</span></div>}</section><section className="users-section"><header><div><p>Usuarios de la empresa</p><h3>Clientes y colaboradores</h3></div><span className="users-section__count">{otherUsers.length} registros</span></header>{isLoading ? <div className="users-empty">Cargando usuarios...</div> : otherUsers.length === 0 ? <div className="users-empty"><Users aria-hidden="true" size={25} /><span>Aún no hay usuarios adicionales registrados.</span></div> : <div className="user-record-list">{otherUsers.map((item) => <UserRecord item={item} key={`${item.recordType}-${item.id}`} onDisable={item.recordType === "membership" && item.status === "active" ? () => void handleDisable(item) : undefined} onRevoke={item.recordType === "invitation" && item.status === "pending" ? () => void handleRevoke(item) : undefined} />)}</div>}</section>{isInviteOpen ? <ManagerInvitationForm isSaving={isSaving} onClose={() => setIsInviteOpen(false)} onSubmit={submitInvitation} /> : null}{error ? <p className="organization-form-error" role="alert">{error}</p> : null}<button className="users-refresh" disabled={isLoading} onClick={() => void loadUsers()} type="button"><RefreshCw aria-hidden="true" size={16} /> Actualizar lista</button></section>
}

function UserRecord({ item, onDisable, onRevoke }: { item: OrganizationUserRecord; onDisable?: () => void; onRevoke?: () => void }) { const isInvitation = item.recordType === "invitation"; return <article className="user-record"><span className="user-record__icon">{isInvitation ? <Clock3 aria-hidden="true" size={19} /> : <UserRound aria-hidden="true" size={19} />}</span><div className="user-record__identity"><strong>{item.displayName || "Sin nombre registrado"}</strong><span><Mail aria-hidden="true" size={14} /> {item.email}</span></div><span className="user-record__role">{item.role === "manager" ? "Manager" : item.role === "admin" ? "Administrador" : "Usuario"}</span><span className={`user-record__status user-record__status--${isInvitation ? "pending" : item.status}`}>{isInvitation ? "Invitación pendiente" : item.status === "active" ? "Activo" : "Desactivado"}</span><small>{isInvitation ? `Registrada: ${formatDate(item.createdAt)}${item.expiresAt ? ` · Expira: ${formatDate(item.expiresAt)}` : ""}` : `Alta: ${formatDate(item.createdAt)}`}</small>{onRevoke ? <button className="icon-button user-record__action" aria-label="Revocar invitación" onClick={onRevoke} type="button"><UserX aria-hidden="true" size={17} /></button> : onDisable ? <button className="icon-button user-record__action" aria-label="Desactivar usuario" onClick={onDisable} type="button"><Ban aria-hidden="true" size={17} /></button> : null}</article> }

function ManagerInvitationForm({ isSaving, onClose, onSubmit }: { isSaving: boolean; onClose: () => void; onSubmit: (name: string, email: string) => Promise<void> }) { const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [error, setError] = useState<string | null>(null); const handleSubmit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(null); try { await onSubmit(name.trim(), email.trim()) } catch (submitError) { setError(submitError instanceof Error ? submitError.message : "No se pudo enviar la invitación.") } }; return <div className="modal-backdrop"><section aria-modal="true" className="organization-form-panel" role="dialog"><header><div><p>Responsable principal</p><h2>Asignar Manager</h2></div><button className="icon-button" onClick={onClose} type="button" aria-label="Cerrar">×</button></header><form onSubmit={handleSubmit}><label className="field"><span>Nombre</span><input autoFocus onChange={(event) => setName(event.target.value)} required value={name} /></label><label className="field"><span>Correo electrónico</span><input onChange={(event) => setEmail(event.target.value)} required type="email" value={email} /></label><p className="form-helper">Se enviará una invitación por correo electrónico y se reservará una plaza para este usuario.</p>{error ? <p className="organization-form-error" role="alert">{error}</p> : null}<footer><button className="button button--secondary" onClick={onClose} type="button">Cancelar</button><button className="button button--primary" disabled={isSaving} type="submit"><UserPlus aria-hidden="true" size={17} /> {isSaving ? "Enviando..." : "Enviar invitación"}</button></footer></form></section></div> }

function OrganizationForm({ editingOrganization, isSaving, onClose, onSubmit }: { editingOrganization: OrganizationSummary | null; isSaving: boolean; onClose: () => void; onSubmit: (input: CreateOrganizationInput) => Promise<void> }) { const [name, setName] = useState(editingOrganization?.name ?? ""); const [seatLimit, setSeatLimit] = useState(String(editingOrganization?.seatLimit ?? 10)); const [error, setError] = useState<string | null>(null); const handleSubmit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(null); try { await onSubmit({ name: name.trim(), seatLimit: Number(seatLimit) }) } catch (submitError) { setError(submitError instanceof Error ? submitError.message : "No se pudo guardar la empresa.") } }; return <div className="modal-backdrop" role="presentation"><section aria-modal="true" className="organization-form-panel" role="dialog"><header><div><p>{editingOrganization ? "Editar empresa" : "Nueva empresa"}</p><h2>{editingOrganization ? "Información básica" : "Registrar empresa"}</h2></div><button className="icon-button" onClick={onClose} type="button" aria-label="Cerrar">×</button></header><form onSubmit={handleSubmit}><label className="field"><span>Nombre de la empresa</span><input autoFocus onChange={(event) => setName(event.target.value)} required value={name} /></label><label className="field"><span>Límite de usuarios</span><input min="1" onChange={(event) => setSeatLimit(event.target.value)} required type="number" value={seatLimit} /></label>{error ? <p className="organization-form-error" role="alert">{error}</p> : null}<footer><button className="button button--secondary" onClick={onClose} type="button">Cancelar</button><button className="button button--primary" disabled={isSaving} type="submit">{isSaving ? "Guardando..." : editingOrganization ? "Guardar cambios" : "Crear empresa"}</button></footer></form></section></div> }
