import { Building2, CalendarDays, CheckCircle2, Clock3, Headphones, MessageSquare, Search, Send, Tag, UserRound, X } from "lucide-react"
import { useEffect, useMemo, useState, type FormEvent } from "react"
import { addFeedbackTicketMessage, getFeedbackTicketMessages, listOrganizationFeedbackTickets } from "../services/feedback"
import { getSupabaseClient } from "../services/supabase"
import type { FeedbackStatus, FeedbackTicket, FeedbackTicketMessage } from "../types/feedback"

const categoryLabels = { problem: "Problema", improvement: "Mejora", suggestion: "Sugerencia", support: "Soporte" } as const
const statusLabels: Record<FeedbackStatus, string> = { open: "Abierto", in_review: "En revisión", in_progress: "En proceso", resolved: "Resuelto", closed: "Cerrado" }
const priorityLabels = { low: "Baja", normal: "Normal", high: "Alta", urgent: "Urgente" } as const
const filterOptions: Array<{ value: "all" | FeedbackStatus; label: string }> = [{ value: "all", label: "Todos" }, { value: "open", label: "Abiertos" }, { value: "in_progress", label: "En proceso" }, { value: "resolved", label: "Resueltos" }, { value: "closed", label: "Cerrados" }]
const formatDate = (value: string) => new Intl.DateTimeFormat("es-MX", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value))
const getInitials = (name: string | null, fallback: string) => { const source = name?.trim() || fallback; const parts = source.split(/\s+/).filter(Boolean); return parts.length > 1 ? `${parts[0][0]}${parts[parts.length - 1][0]}`.toUpperCase() : source.slice(0, 2).toUpperCase() }

export function FeedbackAdminPanel({ organizationId }: { organizationId: string }) {
  const [tickets, setTickets] = useState<FeedbackTicket[]>([]); const [selected, setSelected] = useState<FeedbackTicket | null>(null); const [messages, setMessages] = useState<FeedbackTicketMessage[]>([]); const [loading, setLoading] = useState(true); const [loadingMessages, setLoadingMessages] = useState(false); const [error, setError] = useState<string | null>(null); const [reply, setReply] = useState(""); const [sendingReply, setSendingReply] = useState(false); const [filter, setFilter] = useState<"all" | FeedbackStatus>("all"); const [search, setSearch] = useState("")
  const refresh = async () => { setLoading(true); setError(null); try { setTickets(await listOrganizationFeedbackTickets(organizationId)) } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "No se pudieron cargar los tickets.") } finally { setLoading(false) } }
  useEffect(() => { void refresh(); setSelected(null) }, [organizationId])
  const openTicket = (ticket: FeedbackTicket) => { setSelected(ticket); setMessages([]); setError(null) }
  const filteredTickets = useMemo(() => { const normalized = search.trim().toLowerCase(); return tickets.filter((ticket) => (filter === "all" || ticket.status === filter) && (!normalized || `${ticket.folio} ${ticket.title} ${categoryLabels[ticket.category]} ${statusLabels[ticket.status]} ${priorityLabels[ticket.priority]} ${ticket.creatorName ?? ""}`.toLowerCase().includes(normalized))) }, [filter, search, tickets])
  useEffect(() => {
    if (!selected) return
    let active = true
    setLoadingMessages(true)
    const mergeMessages = (incoming: FeedbackTicketMessage[]) => { setMessages((current) => [...new Map([...current, ...incoming].map((item) => [item.id, item])).values()].sort((left, right) => left.createdAt.localeCompare(right.createdAt))) }
    const channel = getSupabaseClient().channel(`feedback-admin-ticket-${selected.id}`).on("postgres_changes", { event: "INSERT", schema: "public", table: "feedback_ticket_messages", filter: `ticket_id=eq.${selected.id}` }, (payload) => { const row = payload.new as { id?: string; ticket_id?: string; organization_id?: string; author_id?: string; message?: string; created_at?: string }; if (!row.id || !row.ticket_id || !row.organization_id || !row.author_id || !row.message || !row.created_at) return; mergeMessages([{ id: row.id, ticketId: row.ticket_id, organizationId: row.organization_id, authorId: row.author_id, authorName: null, message: row.message, createdAt: row.created_at }]) })
    channel.subscribe((status) => { if (status === "SUBSCRIBED") void getFeedbackTicketMessages(selected.id).then((loaded) => { if (active) mergeMessages(loaded) }).catch(() => { if (active) setError("No se pudo actualizar la conversación.") }) })
    void getFeedbackTicketMessages(selected.id).then((loaded) => { if (active) mergeMessages(loaded) }).catch((loadError) => { if (active) setError(loadError instanceof Error ? loadError.message : "No se pudo cargar la conversación.") }).finally(() => { if (active) setLoadingMessages(false) })
    return () => { active = false; void getSupabaseClient().removeChannel(channel) }
  }, [selected])
  const submitMessage = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!selected || selected.status === "closed" || sendingReply) return; const message = reply.trim(); if (!message) return; setError(null); setSendingReply(true); try { await addFeedbackTicketMessage(selected.id, message); setReply(""); setMessages(await getFeedbackTicketMessages(selected.id)); setTickets(await listOrganizationFeedbackTickets(organizationId)) } catch (submitError) { setError(submitError instanceof Error ? submitError.message : "No se pudo enviar la respuesta.") } finally { setSendingReply(false) } }
  return <section className="support-center support-center--admin" aria-labelledby="admin-feedback-title">
    <header className="support-center__header"><div className="support-center__heading"><span className="support-center__icon"><Headphones aria-hidden="true" size={22} /></span><div><p className="support-center__kicker">Mesa de soporte FleetMaster</p><h2 id="admin-feedback-title">Centro de soporte</h2><span>Seguimiento ejecutivo de las solicitudes de la empresa seleccionada.</span></div></div><span className="support-admin-context"><Building2 aria-hidden="true" size={16} /> Organización actual</span></header>
    <div className="support-center__toolbar"><div className="support-center__filters" aria-label="Filtrar tickets">{filterOptions.map((option) => <button className={filter === option.value ? "is-active" : ""} key={option.value} onClick={() => setFilter(option.value)} type="button">{option.label}{option.value === "all" ? ` ${tickets.length}` : ""}</button>)}</div><label className="support-search"><Search aria-hidden="true" size={17} /><span className="sr-only">Buscar tickets</span><input onChange={(event) => setSearch(event.target.value)} placeholder="Buscar folio, título o creador" value={search} /></label></div>
    <div className="support-workspace"><section className="support-list-panel" aria-labelledby="admin-ticket-list-title"><header><div><p className="support-eyebrow">Bandeja administrativa</p><h3 id="admin-ticket-list-title">Tickets de la empresa</h3></div><span>{filteredTickets.length} {filteredTickets.length === 1 ? "resultado" : "resultados"}</span></header>{loading ? <p className="support-empty">Cargando tickets...</p> : filteredTickets.length === 0 ? <div className="support-empty"><MessageSquare aria-hidden="true" size={27} /><strong>{tickets.length === 0 ? "Esta empresa todavía no tiene tickets" : "No hay coincidencias"}</strong><span>{tickets.length === 0 ? "Las solicitudes aparecerán aquí cuando la empresa cree un ticket." : "Prueba con otro filtro o término de búsqueda."}</span></div> : <div className="support-ticket-list">{filteredTickets.map((ticket) => <button className={`support-ticket${selected?.id === ticket.id ? " is-selected" : ""}`} key={ticket.id} onClick={() => void openTicket(ticket)} type="button"><span className="support-ticket__top"><strong>{ticket.folio}</strong><time>{formatDate(ticket.updatedAt)}</time></span><b>{ticket.title}</b><span className="support-ticket__meta"><em className={`feedback-status feedback-status--${ticket.status}`}>{statusLabels[ticket.status]}</em><small><Tag aria-hidden="true" size={13} /> {priorityLabels[ticket.priority]} · {categoryLabels[ticket.category]}</small></span><span className="support-ticket__creator"><UserRound aria-hidden="true" size={13} /> {ticket.creatorName || "Usuario de la empresa"}</span></button>)}</div>}</section>
      <section className="support-conversation" aria-labelledby="admin-conversation-title">{selected ? <><header className="support-conversation__header"><div><p className="support-eyebrow">Conversación</p><span className="support-conversation__folio">{selected.folio}</span><h3 id="admin-conversation-title">{selected.title}</h3><div className="support-conversation__meta"><em className={`feedback-status feedback-status--${selected.status}`}>{statusLabels[selected.status]}</em><span>{priorityLabels[selected.priority]}</span><span>{categoryLabels[selected.category]}</span><span><CalendarDays aria-hidden="true" size={14} /> {formatDate(selected.createdAt)}</span></div></div><button className="icon-button" aria-label="Cerrar detalle" onClick={() => setSelected(null)} type="button"><X aria-hidden="true" size={18} /></button></header><div className="support-messages">{loadingMessages ? <p className="support-empty">Cargando conversación...</p> : messages.length === 0 ? <p className="support-empty">Aún no hay mensajes en esta conversación.</p> : messages.map((item) => <article className="support-message" key={item.id}><div className="support-message__avatar" aria-hidden="true">{getInitials(item.authorName, "Usuario")}</div><div className="support-message__body"><header><strong>{item.authorName || "Usuario de la empresa"}</strong><time><Clock3 aria-hidden="true" size={13} /> {formatDate(item.createdAt)}</time></header><p>{item.message}</p></div></article>)}</div>{selected.status === "closed" ? <p className="support-closed">Este ticket está cerrado y no acepta nuevas respuestas.</p> : <form className="support-composer" onSubmit={submitMessage}><label className="sr-only" htmlFor="admin-ticket-reply">Escribe un mensaje</label><textarea id="admin-ticket-reply" onChange={(event) => setReply(event.target.value)} placeholder="Escribe una respuesta..." required rows={3} value={reply} /><button className="button button--primary" disabled={sendingReply} type="submit"><Send aria-hidden="true" size={16} /> {sendingReply ? "Enviando..." : "Enviar"}</button></form>}</> : <div className="support-no-selection"><span className="support-no-selection__icon"><MessageSquare aria-hidden="true" size={27} /></span><h3 id="admin-conversation-title">Selecciona un ticket</h3><p>Abre una solicitud para revisar la conversación completa.</p></div>}</section>
      <aside className="support-details-panel"><header><span className="support-details-panel__icon"><CheckCircle2 aria-hidden="true" size={18} /></span><div><p className="support-eyebrow">Ficha ejecutiva</p><h3>Detalles del ticket</h3></div></header>{selected ? <dl><div><dt>Folio</dt><dd>{selected.folio}</dd></div><div><dt>Estado</dt><dd><em className={`feedback-status feedback-status--${selected.status}`}>{statusLabels[selected.status]}</em></dd></div><div><dt>Prioridad</dt><dd>{priorityLabels[selected.priority]}</dd></div><div><dt>Categoría</dt><dd>{categoryLabels[selected.category]}</dd></div><div><dt>Creado por</dt><dd>{selected.creatorName || "Usuario de la empresa"}</dd></div><div><dt>Organización</dt><dd>{selected.organizationId.slice(0, 8)}</dd></div><div><dt>Creado</dt><dd>{formatDate(selected.createdAt)}</dd></div><div><dt>Última actividad</dt><dd>{formatDate(selected.updatedAt)}</dd></div></dl> : <p className="support-details-panel__empty">Los detalles del ticket seleccionado aparecerán aquí.</p>}</aside>
    </div>
    {error ? <p className="feedback-error" role="alert">{error}</p> : null}
  </section>
}
