import { CalendarDays, CheckCircle2, Clock3, Headphones, MessageSquare, Plus, Search, Send, Tag, X } from "lucide-react"
import { useEffect, useMemo, useState, type FormEvent } from "react"
import { addFeedbackTicketMessage, createFeedbackTicket, getFeedbackTicketMessages, listMyFeedbackTickets } from "../services/feedback"
import { getSupabaseClient } from "../services/supabase"
import { feedbackCategories, type FeedbackCategory, type FeedbackStatus, type FeedbackTicket, type FeedbackTicketMessage } from "../types/feedback"

const categoryLabels: Record<FeedbackCategory, string> = { problem: "Problema", improvement: "Mejora", suggestion: "Sugerencia", support: "Soporte" }
const statusLabels: Record<FeedbackStatus, string> = { open: "Abierto", in_review: "En revisión", in_progress: "En proceso", resolved: "Resuelto", closed: "Cerrado" }
const priorityLabels = { low: "Baja", normal: "Normal", high: "Alta", urgent: "Urgente" } as const
const filterOptions: Array<{ value: "all" | FeedbackStatus; label: string }> = [{ value: "all", label: "Todos" }, { value: "open", label: "Abiertos" }, { value: "in_progress", label: "En proceso" }, { value: "resolved", label: "Resueltos" }, { value: "closed", label: "Cerrados" }]
const formatDate = (value: string) => new Intl.DateTimeFormat("es-MX", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value))
const formatDay = (value: string) => new Intl.DateTimeFormat("es-MX", { dateStyle: "medium" }).format(new Date(value))
const getInitials = (name: string | null, fallback: string) => { const source = name?.trim() || fallback; const parts = source.split(/\s+/).filter(Boolean); return parts.length > 1 ? `${parts[0][0]}${parts[parts.length - 1][0]}`.toUpperCase() : source.slice(0, 2).toUpperCase() }

export function FeedbackPanel() {
  const [tickets, setTickets] = useState<FeedbackTicket[]>([]); const [selected, setSelected] = useState<FeedbackTicket | null>(null); const [messages, setMessages] = useState<FeedbackTicketMessage[]>([]); const [isFormOpen, setIsFormOpen] = useState(false); const [loading, setLoading] = useState(true); const [loadingMessages, setLoadingMessages] = useState(false); const [error, setError] = useState<string | null>(null); const [success, setSuccess] = useState<string | null>(null); const [reply, setReply] = useState(""); const [sendingReply, setSendingReply] = useState(false); const [filter, setFilter] = useState<"all" | FeedbackStatus>("all"); const [search, setSearch] = useState("")
  const refresh = async () => { setLoading(true); setError(null); try { setTickets(await listMyFeedbackTickets()) } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "No se pudieron cargar tus tickets.") } finally { setLoading(false) } }
  useEffect(() => { void refresh() }, [])
  const openTicket = (ticket: FeedbackTicket) => { setSelected(ticket); setMessages([]); setError(null) }
  const filteredTickets = useMemo(() => { const normalized = search.trim().toLowerCase(); return tickets.filter((ticket) => (filter === "all" || ticket.status === filter) && (!normalized || `${ticket.folio} ${ticket.title} ${categoryLabels[ticket.category]} ${statusLabels[ticket.status]} ${priorityLabels[ticket.priority]}`.toLowerCase().includes(normalized))) }, [filter, search, tickets])
  useEffect(() => {
    if (!selected) return
    let active = true
    setLoadingMessages(true)
    const mergeMessages = (incoming: FeedbackTicketMessage[]) => { setMessages((current) => [...new Map([...current, ...incoming].map((item) => [item.id, item])).values()].sort((left, right) => left.createdAt.localeCompare(right.createdAt))) }
    const channel = getSupabaseClient().channel(`feedback-ticket-${selected.id}`).on("postgres_changes", { event: "INSERT", schema: "public", table: "feedback_ticket_messages", filter: `ticket_id=eq.${selected.id}` }, (payload) => { const row = payload.new as { id?: string; ticket_id?: string; organization_id?: string; author_id?: string; message?: string; created_at?: string }; if (!row.id || !row.ticket_id || !row.organization_id || !row.author_id || !row.message || !row.created_at) return; mergeMessages([{ id: row.id, ticketId: row.ticket_id, organizationId: row.organization_id, authorId: row.author_id, authorName: null, message: row.message, createdAt: row.created_at }]) })
    channel.subscribe((status) => { if (status === "SUBSCRIBED") void getFeedbackTicketMessages(selected.id).then((loaded) => { if (active) mergeMessages(loaded) }).catch(() => { if (active) setError("No se pudo actualizar la conversación.") }) })
    void getFeedbackTicketMessages(selected.id).then((loaded) => { if (active) mergeMessages(loaded) }).catch((loadError) => { if (active) setError(loadError instanceof Error ? loadError.message : "No se pudo cargar la conversación.") }).finally(() => { if (active) setLoadingMessages(false) })
    return () => { active = false; void getSupabaseClient().removeChannel(channel) }
  }, [selected])
  const submitTicket = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); setError(null); try { const ticket = await createFeedbackTicket(String(form.get("title") ?? "").trim(), String(form.get("category") ?? "problem") as FeedbackCategory, String(form.get("message") ?? "").trim()); setIsFormOpen(false); setSuccess("Ticket creado correctamente."); await refresh(); await openTicket(ticket) } catch (submitError) { setError(submitError instanceof Error ? submitError.message : "No se pudo crear el ticket.") } }
  const submitMessage = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!selected || selected.status === "closed" || sendingReply) return; const message = reply.trim(); if (!message) return; setError(null); setSendingReply(true); try { await addFeedbackTicketMessage(selected.id, message); setReply(""); setMessages(await getFeedbackTicketMessages(selected.id)); setTickets(await listMyFeedbackTickets()) } catch (submitError) { setError(submitError instanceof Error ? submitError.message : "No se pudo enviar la respuesta.") } finally { setSendingReply(false) } }
  return <section className="support-center support-center--client" aria-labelledby="feedback-title">
    <header className="support-center__header"><div className="support-center__heading"><span className="support-center__icon"><Headphones aria-hidden="true" size={22} /></span><div><p className="organization-account-kicker">Centro de soporte</p><h2 id="feedback-title">¿En qué podemos ayudarte?</h2><span>Reporta un problema, solicita una mejora o comparte una sugerencia.</span></div></div><button className="button button--primary" onClick={() => { setIsFormOpen(true); setError(null) }} type="button"><Plus aria-hidden="true" size={17} /> Nuevo ticket</button></header>
    <div className="support-center__toolbar"><div className="support-center__filters" aria-label="Filtrar tickets">{filterOptions.map((option) => <button className={filter === option.value ? "is-active" : ""} key={option.value} onClick={() => setFilter(option.value)} type="button">{option.label}{option.value === "all" ? ` ${tickets.length}` : ""}</button>)}</div><label className="support-search"><Search aria-hidden="true" size={17} /><span className="sr-only">Buscar tickets</span><input onChange={(event) => setSearch(event.target.value)} placeholder="Buscar por folio, título o categoría" value={search} /></label></div>
    <div className="support-workspace"><section className="support-list-panel" aria-labelledby="support-list-title"><header><div><p className="support-eyebrow">Bandeja personal</p><h3 id="support-list-title">Mis tickets</h3></div><span>{filteredTickets.length} {filteredTickets.length === 1 ? "resultado" : "resultados"}</span></header>{loading ? <p className="support-empty">Cargando tickets...</p> : filteredTickets.length === 0 ? <div className="support-empty"><MessageSquare aria-hidden="true" size={27} /><strong>{tickets.length === 0 ? "Aún no tienes tickets" : "No hay coincidencias"}</strong><span>{tickets.length === 0 ? "Cuando necesites ayuda, crea un ticket y te responderemos desde aquí." : "Prueba con otro filtro o término de búsqueda."}</span></div> : <div className="support-ticket-list">{filteredTickets.map((ticket) => <button className={`support-ticket${selected?.id === ticket.id ? " is-selected" : ""}`} key={ticket.id} onClick={() => void openTicket(ticket)} type="button"><span className="support-ticket__top"><strong>{ticket.folio}</strong><time>{formatDay(ticket.updatedAt)}</time></span><b>{ticket.title}</b><span className="support-ticket__meta"><em className={`feedback-status feedback-status--${ticket.status}`}>{statusLabels[ticket.status]}</em><small><Tag aria-hidden="true" size={13} /> {categoryLabels[ticket.category]} · {priorityLabels[ticket.priority]}</small></span></button>)}</div>}</section>
      <section className="support-conversation" aria-labelledby="support-conversation-title">{selected ? <><header className="support-conversation__header"><div><p className="support-eyebrow">Conversación</p><span className="support-conversation__folio">{selected.folio}</span><h3 id="support-conversation-title">{selected.title}</h3><div className="support-conversation__meta"><em className={`feedback-status feedback-status--${selected.status}`}>{statusLabels[selected.status]}</em><span>{categoryLabels[selected.category]}</span><span>{priorityLabels[selected.priority]}</span><span><CalendarDays aria-hidden="true" size={14} /> {formatDate(selected.createdAt)}</span></div></div><button className="icon-button" aria-label="Cerrar detalle" onClick={() => setSelected(null)} type="button"><X aria-hidden="true" size={18} /></button></header><div className="support-messages">{loadingMessages ? <p className="support-empty">Cargando conversación...</p> : messages.length === 0 ? <p className="support-empty">Aún no hay mensajes en esta conversación.</p> : messages.map((item) => <article className="support-message" key={item.id}><div className="support-message__avatar" aria-hidden="true">{getInitials(item.authorName, "FleetMaster")}</div><div className="support-message__body"><header><strong>{item.authorName || "Equipo FleetMaster"}</strong><time><Clock3 aria-hidden="true" size={13} /> {formatDate(item.createdAt)}</time></header><p>{item.message}</p></div></article>)}</div>{selected.status === "closed" ? <p className="support-closed">Este ticket está cerrado y no acepta nuevas respuestas.</p> : <form className="support-composer" onSubmit={submitMessage}><label className="sr-only" htmlFor="client-ticket-reply">Escribe un mensaje</label><textarea id="client-ticket-reply" onChange={(event) => setReply(event.target.value)} placeholder="Escribe un mensaje..." required rows={3} value={reply} /><button className="button button--primary" disabled={sendingReply} type="submit"><Send aria-hidden="true" size={16} /> {sendingReply ? "Enviando..." : "Enviar"}</button></form>}</> : <div className="support-no-selection"><span className="support-no-selection__icon"><MessageSquare aria-hidden="true" size={27} /></span><h3 id="support-conversation-title">Selecciona un ticket</h3><p>Elige una solicitud de la bandeja para consultar la conversación.</p></div>}</section>
      <aside className="support-details-panel"><header><span className="support-details-panel__icon"><CheckCircle2 aria-hidden="true" size={18} /></span><div><p className="support-eyebrow">Contexto</p><h3>Detalles del ticket</h3></div></header>{selected ? <dl><div><dt>Folio</dt><dd>{selected.folio}</dd></div><div><dt>Estado</dt><dd><em className={`feedback-status feedback-status--${selected.status}`}>{statusLabels[selected.status]}</em></dd></div><div><dt>Prioridad</dt><dd>{priorityLabels[selected.priority]}</dd></div><div><dt>Categoría</dt><dd>{categoryLabels[selected.category]}</dd></div><div><dt>Creado</dt><dd>{formatDate(selected.createdAt)}</dd></div><div><dt>Última actividad</dt><dd>{formatDate(selected.updatedAt)}</dd></div></dl> : <p className="support-details-panel__empty">Los detalles del ticket seleccionado aparecerán aquí.</p>}</aside>
    </div>
    {success ? <p className="feedback-success" role="status">{success}</p> : null}{error ? <p className="feedback-error" role="alert">{error}</p> : null}{isFormOpen ? <div className="modal-backdrop"><section className="feedback-form-panel support-form-panel" aria-modal="true" role="dialog"><header><div><p className="organization-account-kicker">Nuevo ticket</p><h2>Cuéntanos qué sucede</h2></div><button className="icon-button" aria-label="Cerrar" onClick={() => setIsFormOpen(false)} type="button"><X aria-hidden="true" size={18} /></button></header><form onSubmit={submitTicket}><label className="field"><span>Título</span><input name="title" maxLength={200} required /></label><label className="field"><span>Categoría</span><select defaultValue="problem" name="category">{feedbackCategories.map((category) => <option key={category} value={category}>{categoryLabels[category]}</option>)}</select></label><label className="field"><span>Mensaje</span><textarea maxLength={5000} name="message" required rows={6} /></label><footer><button className="button button--secondary" onClick={() => setIsFormOpen(false)} type="button">Cancelar</button><button className="button button--primary" type="submit"><Plus aria-hidden="true" size={17} /> Crear ticket</button></footer></form></section></div> : null}
  </section>
}
